// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLDbRFEvBZdAuw8rztZJZD9AxQvz3TmMY',
    appId: '1:945232819184:web:3a7cddd47d875fc0f66335',
    messagingSenderId: '945232819184',
    projectId: 'embs-77c59',
    authDomain: 'embs-77c59.firebaseapp.com',
    storageBucket: 'embs-77c59.firebasestorage.app',
    measurementId: 'G-8YZH5KVS2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXQok4GcTHbk0VK33wkLNctQfQJbCJRsc',
    appId: '1:945232819184:android:104415426a445ac6f66335',
    messagingSenderId: '945232819184',
    projectId: 'embs-77c59',
    storageBucket: 'embs-77c59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjhuVgUpxOLEMDyF0xGr8FiTt3IKF9lUc',
    appId: '1:945232819184:ios:6d56d469e797a1ddf66335',
    messagingSenderId: '945232819184',
    projectId: 'embs-77c59',
    storageBucket: 'embs-77c59.firebasestorage.app',
    iosBundleId: 'com.example.tounsicare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjhuVgUpxOLEMDyF0xGr8FiTt3IKF9lUc',
    appId: '1:945232819184:ios:6d56d469e797a1ddf66335',
    messagingSenderId: '945232819184',
    projectId: 'embs-77c59',
    storageBucket: 'embs-77c59.firebasestorage.app',
    iosBundleId: 'com.example.tounsicare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLDbRFEvBZdAuw8rztZJZD9AxQvz3TmMY',
    appId: '1:945232819184:web:94942d5eadec14e2f66335',
    messagingSenderId: '945232819184',
    projectId: 'embs-77c59',
    authDomain: 'embs-77c59.firebaseapp.com',
    storageBucket: 'embs-77c59.firebasestorage.app',
    measurementId: 'G-SFF1EEKD76',
  );
}
